# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

            
      - name: Restore NuGet packages
        working-directory: .
        run: nuget restore unit-testing-using-nunit.sln
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
        
      - name: dowload sonarscanner
        working-directory: .
        shell: pwsh
        run: |
             New-Item -Path .\sonar\scanner -ItemType Directory
             Invoke-RestMethod -Uri 'https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/4.10.0.19059/sonar-scanner-msbuild-4.10.0.19059-net46.zip' -OutFile '.\sonar\scanner\sonar-scanner-msbuild-4.10.0.19059-net46.zip'
             expand-archive -path '.\sonar\scanner\sonar-scanner-msbuild-4.10.0.19059-net46.zip' -destinationpath '.\sonar\scanner'    
      
      
      - name: dowload dotcover
        working-directory: D:\a\Nunit\Nunit\
        run: |
             New-Item -Path D:\a\Nunit\Nunit\dotcover -ItemType Directory
             Invoke-RestMethod -Uri 'https://download.jetbrains.com/resharper/dotUltimate.2021.1.5/JetBrains.dotCover.CommandLineTools.2021.1.5.zip' -OutFile 'D:\a\Nunit\Nunit\dotcover\JetBrains.dotCover.CommandLineTools.2021.1.5.zip'
             expand-archive -path 'D:\a\Nunit\Nunit\dotcover\JetBrains.dotCover.CommandLineTools.2021.1.5.zip' -destinationpath 'D:\a\Nunit\Nunit\dotcover'
    
      - name: dowload nunit
        working-directory: D:\a\Nunit\Nunit\
        run: |
             New-Item -Path D:\a\Nunit\Nunit\Nunitconsole -ItemType Directory
             Invoke-RestMethod -Uri 'https://github.com/nunit/nunit-console/releases/download/v3.12/NUnit.Console-3.12.0.zip' -OutFile 'D:\a\Nunit\Nunit\Nunitconsole\NUnit.Console-3.12.0.zip'
             expand-archive -path 'D:\a\Nunit\Nunit\Nunitconsole\NUnit.Console-3.12.0.zip' -destinationpath 'D:\a\Nunit\Nunit\Nunitconsole'
     
      - name: powershell
        run: |
             Get-ChildItem -path "D:\a\Nunit\Nunit"
             
      - name: powershell
        run: |
             Get-ChildItem -path "D:\a\Nunit\Nunit\Nunitconsole" -Recurse
             
      - name: powershell
        run: |
             Get-ChildItem -path "D:\a\Nunit\Nunit\dotcover" -Recurse
             
      - name: Begin sonar
        shell: pwsh
        run: |
             D:\a\Nunit\Nunit\sonar\scanner\SonarScanner.MSBuild.exe begin /k:"test" /d:sonar.host.url="http://18.223.255.187:9000/" /d:sonar.login="468e915bea1f082d467573a002519263bc54598d" /d:sonar.cs.nunit.reportsPaths="reports/nunit_results.xml" /d:sonar.cs.dotcover.reportsPaths="./SonarQube.html" /d:sonar.test.inclusions="**/*.Tests/**/*" /d:sonar.exclusions="**/*.test,**/vendor/**"  
             MSBuild.exe /target:Rebuild /p:RunCodeAnalysis=True /p:RunCodeAnalysisOnThisProject=true /p:CollectCoverage=true D:\a\Nunit\Nunit\unit-testing-using-nunit.sln
      
      - name: nunit tests
        run: D:\a\Nunit\Nunit\Nunitconsole\bin\net35\nunit3-console.exe unit-testing-using-nunit1.csproj --result=reports\nunit_results.xml;format=nunit2 --output=reports\nunit_out.log --framework=net-4.5 --config=%configuration% --dispose-runners --workers=10
             
             
      - name: Dot cover code coverage
        run: D:\a\Nunit\Nunit\dotcover\dotCover.exe cover 
             /TargetExecutable="D:\a\Nunit\Nunit\Nunitconsole\bin\net35\nunit3-console.exe"
            /TargetArguments="D:\a\Nunit\Nunit\PrimeService.Tests/bin/SonarQube/PrimeService.Tests.dll"
           /Output="./SonarQube.html"
          /ReportType=HTML
             
    
      - name: powershell
        shell: pwsh
        run: | 
             Get-ChildItem -path "D:\a\Nunit\Nunit\PrimeService.Tests/bin"
     
     
     
     
      - name: end analysis
        run:  /home/runner/work/Nunit/Nunit/sonar/scanner/SonarScanner.MSBuild.exe end /d:sonar.login="468e915bea1f082d467573a002519263bc54598d"
       
