name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    #- name: Restore NuGet packages
     # working-directory: .
      #run: nuget restore unit-testing-using-nunit.sln
      
    #- name: NUnit
    #  run: dotnet new nunit
      
    #- name: Restore dependencies 
     # working-directory: ./core/getting-started/unit-testing-using-nunit/unit-testing-using-nunit.sln
      #run: dotnet restore
    - name: Build
      working-directory: ./
      run: dotnet build  unit-testing-using-nunit1.csproj
      
    - name: add package Microsoft.NET.Test.Sdk
      run: dotnet add unit-testing-using-nunit1.csproj package Microsoft.NET.Test.Sdk --version 16.10.0 
      
    - name: add package Nunit3Consoler
      run: dotnet add unit-testing-using-nunit1.csproj package NUnit.ConsoleRunner --version 3.12.0
      
    - name: add package Nunit3TestAdapter
      run: dotnet add unit-testing-using-nunit1.csproj package Nunit3TestAdapter
      
    
      
    - name: add package NUnit
      run: dotnet add unit-testing-using-nunit1.csproj package NUnit
    
    - name: add test logger package 
      run: dotnet add unit-testing-using-nunit1.csproj package NunitXml.TestLogger --version 3.0.107
      
    #- name: add package NUnit
     # run: dotnet add unit-testing-using-nunit1.csproj package TeamCity.dotcover
      
    - name: Test
      run: dotnet test unit-testing-using-nunit.sln --logger:"trx;LogFileName=testresult.xml"
      #run: dotnet test unit-testing-using-nunit.sln --logger trx
      #run: dotnet test unit-testing-using-nunit.sln --collect "Code Coverage"
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
          # Artifact name
         name: artifact 
         path: D:\a\Nunit\Nunit\unit-testing-using-nunit1.csproj
         
   
    

    #- name: dotnet cover  
     # uses: dodopizza/dotcover-action@v1
      #with:
         #dotCoverCommand: help cover coverage.xml
       #  dotCoverCommand: dotnet--output=./CodeCoverageReport.xml --reportType=XML -- test "./unit-testing-using-nunit1.csproj"

    - name: Install dotcove CLI
      run:  dotnet tool install JetBrains.dotCover.GlobalTool -g

      
    - name: Cover report
      run: |
            Get-ChildItem -Path "D:\a\Nunit\Nunit\" -Recurse
            dotnet dotcover test --dcXML="./config.xml"



       

 
    - name: 'Publish code coverage results'
      uses: actions/upload-artifact@v2.2.3
      with:
          name: CoverageReport
          path: ./config.xml 

 
