name: .NET


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Restore NuGet packages
      working-directory: .
      run: nuget restore unit-testing-using-nunit.sln
      
    #- name: NUnit
    #  run: dotnet new nunit
      
    #- name: Restore dependencies 
     # working-directory: ./core/getting-started/unit-testing-using-nunit/unit-testing-using-nunit.sln
      #run: dotnet restore
    - name: add package Dotcover
      run: dotnet add package TeamCity.dotCover --version 2019.1.3
    - name: Build
      working-directory: ./
      run: dotnet msbuild  unit-testing-using-nunit1.csproj
      
    - name: add package Microsoft.NET.Test.Sdk
      run: dotnet add unit-testing-using-nunit1.csproj package Microsoft.NET.Test.Sdk --version 16.10.0 
      
    - name: add package Nunit3Consoler
      run: dotnet add package NUnit.Console --version 3.12.0
      
    - name: add package Nunit3TestAdapter
      run: dotnet add unit-testing-using-nunit1.csproj package Nunit3TestAdapter
      
    
      
    - name: add package NUnit
      run: dotnet add unit-testing-using-nunit1.csproj package NUnit
    
    - name: add test logger package 
      run: dotnet add unit-testing-using-nunit1.csproj package NunitXml.TestLogger --version 3.0.107
      
    #- name: add package NUnit
     # run: dotnet add unit-testing-using-nunit1.csproj package TeamCity.dotcover
      
    #- name: Test
      #run: nunit3-console.exe --result=NUnitResults.xml
     # run: dotnet test unit-testing-using-nunit.sln --logger:"trx;LogFileName=testresult.xml"
      #run: dotnet test unit-testing-using-nunit.sln --logger trx
      #run: dotnet test unit-testing-using-nunit.sln --collect "Code Coverage"
      
   
         
    - name: Sonar install 
      run: dotnet tool install --global dotnet-sonarscanner
      
    - name: Sonar begin
      run: |
           dotnet sonarscanner begin /k:".NetProject" /d:sonar.host.url="http://13.59.238.74:9000/" /d:sonar.login="56b95070f000082b0ab8e126a6c5209549826dbf" /d:sonar.cs.dotcover.reportsPaths="./CodeCoverageReport.html" /d:sonar.cs.nunit.reportsPaths="./testresult.xml"  
           dotnet msbuild unit-testing-using-nunit.sln
   
  
    - name: Test
      #run: nunit3-console.exe --result=NUnitResults.xml
      #run: dotnet test unit-testing-using-nunit.sln --logger trx
      run: |
           dotnet test unit-testing-using-nunit.sln --logger:"trx;LogFileName=testresult.xml"
           mv /home/runner/work/Nunit/Nunit/PrimeService.Tests/TestResults/testresult.xml ./testresult.xml
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
          # Artifact name
         name: artifact 
         path: /home/runner/work/Nunit/Nunit/PrimeService.Tests/TestResults/testresult.xml
      
    - name: dotnet cover  
      uses: dodopizza/dotcover-action@v1
      with:
         #dotCoverCommand: help cover coverage.xml
         dotCoverCommand: dotnet --output=./CodeCoverageReport.html --reportType=HTML -- test "./unit-testing-using-nunit1.csproj" 
      

 
    - name: 'Publish code coverage results'
      uses: actions/upload-artifact@v2.2.3
      with:
          name: CoverageReport
          path: ./CodeCoverageReport.html

    - name: Sonar end
      run: dotnet sonarscanner end /d:sonar.login="56b95070f000082b0ab8e126a6c5209549826dbf"
